# Generated by Django 4.1.9 on 2023-05-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premios', models.CharField(help_text='Pon los premios que puede ganar un director (ej. El Oscar)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='book',
            name='Premios',
            field=models.ManyToManyField(help_text='Selecciona los premios que se mostraran.', to='catalog.premio'),
        ),
    ]
