# Generated by Django 4.1.9 on 2023-05-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_instanciapelicula_alter_pelicula_sipnosis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstanciaPelicula',
        ),
    ]
