# Generated by Django 4.1.9 on 2023-05-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_director_alter_pelicula_director_delete_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Director',
            new_name='Directores',
        ),
    ]
