# Generated by Django 4.1.9 on 2023-05-19 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_director_directores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directores',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identificador unico.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identificador unico.', primary_key=True, serialize=False),
        ),
    ]
