# Generated by Django 4.1.9 on 2023-05-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_pelicula_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='directores',
            name='peliculas',
            field=models.ManyToManyField(to='catalog.pelicula'),
        ),
    ]
