# Generated by Django 4.1.9 on 2023-05-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_directores_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directores',
            name='peliculas',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.pelicula'),
        ),
    ]
